### ISSUE TITLE
FeatureRequest: Brsar extract and pack

### ISSUE THREAD

**Issue by Deflaktor** [libertyernie/brawllib-wit#1]
Is this tool still in development? I'm looking for a cli tool to extract and pack brsar files. 

If this feature would be available, the tool would be integrated into https://github.com/FortuneStreetModding/csmm-qt to enable people to have their custom map music for the game Fortune Street.

**Comment by libertyernie** [comment]
This is something BrawlCrate can already do, right? If so, it shouldn't be too hard, at least on Windows. If you could send me an example brsar file (by email is fine) that would help.

**Comment by Deflaktor** [comment]
Oh damn, since CSMM-QT is a cross-platform tool we would need it for Windows, Linux and Mac-OS. I guess this isnt possible then, is it?

**Comment by libertyernie** [comment]
The two things that would (probably) have to change is that BrawlLib uses .NET Framework 4.x, not .NET Core, and that it makes assumptions in its pointer arithmetic that pointers will always be 32 bits. At that point, it might be easier for someone to track down the relevant code and rewrite it in C.

It might be possible to run it on a 32-bit version of Mono, though. That would rule out macOS, I think, but most Linux would still work.

**Comment by Deflaktor** [comment]
Thanks for the analysis. I guess we try to rewrite the essential parts that are needed.
